### ISSUE TITLE
Console Logging

### ISSUE THREAD

**Issue by leecannon** [Kiakra/Kiragine#3]
Why not use the standard libraries [std.log](https://github.com/ziglang/zig/blob/master/lib/std/log.zig)?

**Comment by Kiakra** [comment]
At the time i was coding the logging i was not aware of `std.log`, i will take a look and see if it'll work as i want to

**Comment by Kiakra** [comment]
It looks like i can override the `log` function, i will implement this and probably gonna rid of the old logging code

**Comment by Kiakra** [comment]
I override the `log` function, to use it there is a one little todo, [see](https://github.com/Kiakra/Kiragine/blob/master/examples/logging.zig).
